server:
  port: 8001

spring:
  dubbo:
    scan: com.cnblogs.yjmyzz.service
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
