server:
    port: 8001

logging:
    level:
        root: DEBUG
        tk.mybatis: DEBUG
        com.alibaba.dubbo: ERROR
        org.apache.zookeeper: ERROR
    file: "/var/log/application/dubbo-provider.log"

spring:
  dubbo:
    scan: com.cnblogs.yjmyzz.service
    application:
        name: provider
    registry:
        address: zookeeper://127.0.0.1:2181
    protocol:
        name: dubbo
        port: 20880
  main:
    banner-mode: "off"
  devtools:
    restart:
      trigger-file: .trigger

druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://localhost:3306/study?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: A1b2c3@def.com
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true
    slave:
        url: jdbc:mysql://localhost:3306/study_slave?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: A1b2c3@def.com
        initial-size: 5
        min-idle: 1
        max-active: 20
        test-on-borrow: true

mybatis:
    type-aliases-package: com.cnblogs.yjmyzz.service.dao.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.cnblogs.yjmyzz.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

management:
  security:
    enabled: false
  port: 9001